{{- if .Values.litefuse.web.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "litefuse.fullname" . }}-web-pdb
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "litefuse.labels" . | nindent 4 }}
  {{- with (coalesce .Values.litefuse.web.deployment.annotations .Values.litefuse.deployment.annotations) }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.litefuse.web.pdb.minAvailable }}
  minAvailable: {{ .Values.litefuse.web.pdb.minAvailable }}
  {{- end  }}
  {{- if or .Values.litefuse.web.pdb.maxUnavailable (not .Values.litefuse.web.pdb.minAvailable) }}
  maxUnavailable: {{ .Values.litefuse.web.pdb.maxUnavailable | default 1 }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "litefuse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
