{{- if .Values.litefuse.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litefuse.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "litefuse.labels" . | nindent 4 }}
  {{- with .Values.litefuse.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.litefuse.serviceAccount.automountServiceAccountToken }}
{{- end }}
